# Config Options
markdown: redcarpet
sass:
  style: :compressed
gems:
    - jekyll-sitemap

# Metadata
name: "Muhlenberg College Computer Science Club"
keywords:
    - "muhlenberg college"
    - "computer science"
author: "Muhlenberg College Computer Science Club"
description: "Projects from Muhlenberg Computer Science."
