# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6ca601dfa0e8b4f5fddc6fbc8ae57a3c317dc48c1045d1a79caf9c53eec89422c59a96dab9190c93b87d40f3b7ff35297b0c0c31780c11bad3fccadf64f891b6

test:
  secret_key_base: 67be1acbff2ed4da80bc78c887d166bc9abb758a232bdf92090df6edbdcba27a0bb74e67afb06daa4b6c72a526faa9b92b8db1667d2e1268fe8a62ee9d544e7b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
